
services: 
  leaderboard-db:
    container_name: leaderboard-db
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - leaderboard-network
    ports:
      - "3306:3306"
    volumes:
      - leaderboard_db:/var/lib/mysql
      - /home/sbtphadmin/sbtph_leaderboard/database:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  leaderboard-backend:
    build: 
      context: ../../backend 
      dockerfile: Dockerfile
    image: robudex17/leaderboard-backend 
    container_name: leaderboard-backend
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_HOST:  leaderboard-db
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET} 
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      PORT: ${CONTAINER_BACKEND_PORT}
    ports:
      - "${HOST_BACKEND_PORT}:${CONTAINER_BACKEND_PORT}"  

        
    depends_on: 
      - leaderboard-db
    networks:
      - leaderboard-network
  leaderboard-frontend:
    build:
      context: ../../frontend/sbtph-sales-leaderboard-app
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_API_URL: ${NUXT_PUBLIC_API_URL}
        NUXT_PUBLIC_SOCKET_IO_URL: ${NUXT_PUBLIC_SOCKET_IO_URL}
        
    image: robudex17/leaderboard-frontend 
    container_name: leaderboard-frontend
    ports:
    - "${HOST_FRONTEND_PORT}:3000"
    depends_on: 
      - leaderboard-backend
    networks:
      - leaderboard-network

volumes:
  leaderboard_db: {}

networks:
  leaderboard-network: {}
