<?php
$servername = "localhost";
$username = "python";
$password = "sbtph@2018";
$dbname = "sbtph_leaderboard"; // Replace with your database name

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Data array

$data = [
    
    ["year" => 2023, "month" => "January", "db_name" => "RUSTAN", "memo-score" => 1, "feedback-score" => 4.570, "ID" => 2394],
    ["year" => 2023, "month" => "January", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2470],
    ["year" => 2023, "month" => "January", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2856],
    ["year" => 2023, "month" => "January", "db_name" => "RUFFY", "memo-score" => 3, "feedback-score" => 4.690, "ID" => 7870],
    ["year" => 2023, "month" => "January", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 2852],
    ["year" => 2023, "month" => "January", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.850, "ID" => 11422],
    ["year" => 2023, "month" => "January", "db_name" => "JOMAN", "memo-score" => 3, "feedback-score" => 4.810, "ID" => 2858],
    ["year" => 2023, "month" => "January", "db_name" => "JHUN", "memo-score" => 0, "feedback-score" => 4.340, "ID" => 3002],
    ["year" => 2023, "month" => "January", "db_name" => "CHRIS", "memo-score" => 3, "feedback-score" => 4.975, "ID" => 10359],
    ["year" => 2023, "month" => "January", "db_name" => "KATHY", "memo-score" => 1, "feedback-score" => 4.135, "ID" => null],
    ["year" => 2023, "month" => "January", "db_name" => "CCUNANAN", "memo-score" => 0, "feedback-score" => 4.320, "ID" => 9721],
    ["year" => 2023, "month" => "January", "db_name" => "ARLENE", "memo-score" => 0, "feedback-score" => 4.940, "ID" => 8059],
    ["year" => 2023, "month" => "January", "db_name" => "EZEKIEL", "memo-score" => 0, "feedback-score" => 3.830, "ID" => null],
    ["year" => 2023, "month" => "January", "db_name" => "XANDER", "memo-score" => 0, "feedback-score" => 4.825, "ID" => null],
    ["year" => 2023, "month" => "January", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 4933],
    ["year" => 2023, "month" => "January", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11421],
    ["year" => 2023, "month" => "January", "db_name" => "BRY", "memo-score" => 1, "feedback-score" => 4.750, "ID" => 2472],
    ["year" => 2023, "month" => "January", "db_name" => "PJ", "memo-score" => 0, "feedback-score" => 4.825, "ID" => 5561],
    ["year" => 2023, "month" => "January", "db_name" => "KEN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => null],
    ["year" => 2023, "month" => "January", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.705, "ID" => 4930],
    ["year" => 2023, "month" => "January", "db_name" => "DON", "memo-score" => 1, "feedback-score" => 4.810, "ID" => 2846],
    ["year" => 2023, "month" => "January", "db_name" => "JOHNCRIS", "memo-score" => 1, "feedback-score" => 4.530, "ID" => null],
    ["year" => 2023, "month" => "January", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.630, "ID" => 9777],
    ["year" => 2023, "month" => "January", "db_name" => "ROMANO", "memo-score" => 0, "feedback-score" => 4.410, "ID" => null],

    ["year" => 2023, "month" => "February", "db_name" => "RUSTAN", "memo-score" => 3, "feedback-score" => 4.695, "ID" => 2394],
    ["year" => 2023, "month" => "February", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.930, "ID" => 2470],
    ["year" => 2023, "month" => "February", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2856],
    ["year" => 2023, "month" => "February", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2023, "month" => "February", "db_name" => "MHEL", "memo-score" => 3, "feedback-score" => 4.815, "ID" => 2852],
    ["year" => 2023, "month" => "February", "db_name" => "RANDY", "memo-score" => 3, "feedback-score" => 4.780, "ID" => 11422],
    ["year" => 2023, "month" => "February", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.500, "ID" => 2858],
    ["year" => 2023, "month" => "February", "db_name" => "JHUN", "memo-score" => 3, "feedback-score" => 4.380, "ID" => 3002],
    ["year" => 2023, "month" => "February", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.890, "ID" => 10359],
    ["year" => 2023, "month" => "February", "db_name" => "KATHY", "memo-score" => 3, "feedback-score" => 4.500, "ID" => null],
    ["year" => 2023, "month" => "February", "db_name" => "CCUNANAN", "memo-score" => 1, "feedback-score" => 4.920, "ID" => 9721],
    ["year" => 2023, "month" => "February", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.440, "ID" => 8059],
    ["year" => 2023, "month" => "February", "db_name" => "EZEKIEL", "memo-score" => 5, "feedback-score" => 3.760, "ID" => null],
    ["year" => 2023, "month" => "February", "db_name" => "XANDER", "memo-score" => 1, "feedback-score" => 4.280, "ID" => null],
    ["year" => 2023, "month" => "February", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 4933],
    ["year" => 2023, "month" => "February", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "February", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 4.225, "ID" => 2472],
    ["year" => 2023, "month" => "February", "db_name" => "PJ", "memo-score" => 1, "feedback-score" => 4.890, "ID" => 5561],
    ["year" => 2023, "month" => "February", "db_name" => "KEN", "memo-score" => 5, "feedback-score" => 4.395, "ID" => null],
    ["year" => 2023, "month" => "February", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.720, "ID" => 4930],
    ["year" => 2023, "month" => "February", "db_name" => "DON", "memo-score" => 3, "feedback-score" => 4.605, "ID" => 2846],
    ["year" => 2023, "month" => "February", "db_name" => "JOHNCRIS", "memo-score" => 1, "feedback-score" => 4.500, "ID" => null],
    ["year" => 2023, "month" => "February", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.520, "ID" => 9777],
    ["year" => 2023, "month" => "February", "db_name" => "ROMANO", "memo-score" => 1, "feedback-score" => 4.335, "ID" => null],

    ["year" => 2023, "month" => "March", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.670, "ID" => 2394],
    ["year" => 2023, "month" => "March", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2470],
    ["year" => 2023, "month" => "March", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2856],
    ["year" => 2023, "month" => "March", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.825, "ID" => 7870],
    ["year" => 2023, "month" => "March", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2852],
    ["year" => 2023, "month" => "March", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.825, "ID" => 11422],
    ["year" => 2023, "month" => "March", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 2858],
    ["year" => 2023, "month" => "March", "db_name" => "CCUNANAN", "memo-score" => 0, "feedback-score" => 4.760, "ID" => 9721],
    ["year" => 2023, "month" => "March", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.210, "ID" => 3002],
    ["year" => 2023, "month" => "March", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.825, "ID" => 10359],
    ["year" => 2023, "month" => "March", "db_name" => "KATHY", "memo-score" => 5, "feedback-score" => 4.970, "ID" => null],
    ["year" => 2023, "month" => "March", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 8059],
    ["year" => 2023, "month" => "March", "db_name" => "EZEKIEL", "memo-score" => 5, "feedback-score" => 3.280, "ID" => null],
    ["year" => 2023, "month" => "March", "db_name" => "XANDER", "memo-score" => 0, "feedback-score" => 3.470, "ID" => null],
    ["year" => 2023, "month" => "March", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 4933],
    ["year" => 2023, "month" => "March", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "March", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 4.410, "ID" => 2472],
    ["year" => 2023, "month" => "March", "db_name" => "PJ", "memo-score" => 0, "feedback-score" => 4.705, "ID" => 5561],
    ["year" => 2023, "month" => "March", "db_name" => "KEN", "memo-score" => 5, "feedback-score" => 4.870, "ID" => null],
    ["year" => 2023, "month" => "March", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.715, "ID" => 4930],
    ["year" => 2023, "month" => "March", "db_name" => "DON", "memo-score" => 3, "feedback-score" => 4.880, "ID" => 2846],
    ["year" => 2023, "month" => "March", "db_name" => "JOHNCRIS", "memo-score" => 0, "feedback-score" => 4.705, "ID" => null],
    ["year" => 2023, "month" => "March", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.785, "ID" => 9777],
    ["year" => 2023, "month" => "March", "db_name" => "ROMANO", "memo-score" => 0, "feedback-score" => 4.355, "ID" => null],

    ["year" => 2023, "month" => "April", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.710, "ID" => 2394],
    ["year" => 2023, "month" => "April", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2470],
    ["year" => 2023, "month" => "April", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2856],
    ["year" => 2023, "month" => "April", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 7870],
    ["year" => 2023, "month" => "April", "db_name" => "XANDER", "memo-score" => 0, "feedback-score" => 4.880, "ID" => null],
    ["year" => 2023, "month" => "April", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2852],
    ["year" => 2023, "month" => "April", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.820, "ID" => 11422],
    ["year" => 2023, "month" => "April", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 2858],
    ["year" => 2023, "month" => "April", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.375, "ID" => 9721],
    ["year" => 2023, "month" => "April", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.215, "ID" => 3002],
    ["year" => 2023, "month" => "April", "db_name" => "CHRIS", "memo-score" => 3, "feedback-score" => 4.940, "ID" => 10359],
    ["year" => 2023, "month" => "April", "db_name" => "KATHY", "memo-score" => 5, "feedback-score" => 4.765, "ID" => null],
    ["year" => 2023, "month" => "April", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.565, "ID" => 8059],
    ["year" => 2023, "month" => "April", "db_name" => "EZEKIEL", "memo-score" => 5, "feedback-score" => 4.085, "ID" => null],
    ["year" => 2023, "month" => "April", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.855, "ID" => 4933],
    ["year" => 2023, "month" => "April", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "April", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.645, "ID" => 6379],
    ["year" => 2023, "month" => "April", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 4.605, "ID" => 2472],
    ["year" => 2023, "month" => "April", "db_name" => "PJ", "memo-score" => 0, "feedback-score" => 4.070, "ID" => 5561],
    ["year" => 2023, "month" => "April", "db_name" => "KEN", "memo-score" => 5, "feedback-score" => 4.405, "ID" => null],
    ["year" => 2023, "month" => "April", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 4930],
    ["year" => 2023, "month" => "April", "db_name" => "ROMANO", "memo-score" => 0, "feedback-score" => 4.765, "ID" => null],
    ["year" => 2023, "month" => "April", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.665, "ID" => 2846],
    ["year" => 2023, "month" => "April", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.425, "ID" => null],
    ["year" => 2023, "month" => "April", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.020, "ID" => 9777],

    ["year" => 2023, "month" => "May", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.780, "ID" => 2394],
    ["year" => 2023, "month" => "May", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2470],
    ["year" => 2023, "month" => "May", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2856],
    ["year" => 2023, "month" => "May", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 7870],
    ["year" => 2023, "month" => "May", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.880, "ID" => null],
    ["year" => 2023, "month" => "May", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.385, "ID" => 2852],
    ["year" => 2023, "month" => "May", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.825, "ID" => 11422],
    ["year" => 2023, "month" => "May", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 2858],
    ["year" => 2023, "month" => "May", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 9721],
    ["year" => 2023, "month" => "May", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.320, "ID" => 3002],
    ["year" => 2023, "month" => "May", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 10359],
    ["year" => 2023, "month" => "May", "db_name" => "KATHY", "memo-score" => 5, "feedback-score" => 4.465, "ID" => null],
    ["year" => 2023, "month" => "May", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 8059],
    ["year" => 2023, "month" => "May", "db_name" => "EZEKIEL", "memo-score" => 5, "feedback-score" => 4.915, "ID" => null],
    ["year" => 2023, "month" => "May", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 4933],
    ["year" => 2023, "month" => "May", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "May", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.470, "ID" => 6379],
    ["year" => 2023, "month" => "May", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.415, "ID" => 2472],
    ["year" => 2023, "month" => "May", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.095, "ID" => 5561],
    ["year" => 2023, "month" => "May", "db_name" => "KEN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => null],
    ["year" => 2023, "month" => "May", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.545, "ID" => 4930],
    ["year" => 2023, "month" => "May", "db_name" => "ROMANO", "memo-score" => 5, "feedback-score" => 4.880, "ID" => null],
    ["year" => 2023, "month" => "May", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 2846],
    ["year" => 2023, "month" => "May", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.530, "ID" => null],
    ["year" => 2023, "month" => "May", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.600, "ID" => 9777],

    ["year" => 2023, "month" => "June", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.860, "ID" => 2394],
    ["year" => 2023, "month" => "June", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.500, "ID" => 2470],
    ["year" => 2023, "month" => "June", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 2856],
    ["year" => 2023, "month" => "June", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2023, "month" => "June", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.825, "ID" => null],
    ["year" => 2023, "month" => "June", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.855, "ID" => 2852],
    ["year" => 2023, "month" => "June", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.800, "ID" => 11422],
    ["year" => 2023, "month" => "June", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2858],
    ["year" => 2023, "month" => "June", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2023, "month" => "June", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 3.930, "ID" => 3002],
    ["year" => 2023, "month" => "June", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 10359],
    ["year" => 2023, "month" => "June", "db_name" => "KATHY", "memo-score" => 5, "feedback-score" => 4.235, "ID" => null],
    ["year" => 2023, "month" => "June", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 8059],
    ["year" => 2023, "month" => "June", "db_name" => "EZEKIEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => null],
    ["year" => 2023, "month" => "June", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.000, "ID" => 4933],
    ["year" => 2023, "month" => "June", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "June", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.825, "ID" => 6379],
    ["year" => 2023, "month" => "June", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 3.355, "ID" => 2472],
    ["year" => 2023, "month" => "June", "db_name" => "PJ", "memo-score" => 3, "feedback-score" => 4.700, "ID" => 5561],
    ["year" => 2023, "month" => "June", "db_name" => "KEN", "memo-score" => 3, "feedback-score" => 3.855, "ID" => null],
    ["year" => 2023, "month" => "June", "db_name" => "DARWIN", "memo-score" => 1, "feedback-score" => 5.000, "ID" => 4930],
    ["year" => 2023, "month" => "June", "db_name" => "ROMANO", "memo-score" => 5, "feedback-score" => 4.880, "ID" => null],
    ["year" => 2023, "month" => "June", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 3.855, "ID" => 2846],
    ["year" => 2023, "month" => "June", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.425, "ID" => null],
    ["year" => 2023, "month" => "June", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.310, "ID" => 9777],

    ["year" => 2023, "month" => "July", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.860, "ID" => 2394],
    ["year" => 2023, "month" => "July", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 2470],
    ["year" => 2023, "month" => "July", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2856],
    ["year" => 2023, "month" => "July", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2023, "month" => "July", "db_name" => "XANDER", "memo-score" => 1, "feedback-score" => 4.590, "ID" => null],
    ["year" => 2023, "month" => "July", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.805, "ID" => 2852],
    ["year" => 2023, "month" => "July", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.820, "ID" => 11422],
    ["year" => 2023, "month" => "July", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2858],
    ["year" => 2023, "month" => "July", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2023, "month" => "July", "db_name" => "JHUN", "memo-score" => 3, "feedback-score" => 4.690, "ID" => 3002],
    ["year" => 2023, "month" => "July", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 10359],
    ["year" => 2023, "month" => "July", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.380, "ID" => 8059],
    ["year" => 2023, "month" => "July", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 4933],
    ["year" => 2023, "month" => "July", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "July", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.765, "ID" => 6379],
    ["year" => 2023, "month" => "July", "db_name" => "BRY", "memo-score" => 0, "feedback-score" => 4.875, "ID" => 2472],
    ["year" => 2023, "month" => "July", "db_name" => "PJ", "memo-score" => 0, "feedback-score" => 4.630, "ID" => 5561],
    ["year" => 2023, "month" => "July", "db_name" => "KEN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => null],
    ["year" => 2023, "month" => "July", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 4930],
    ["year" => 2023, "month" => "July", "db_name" => "ROMANO", "memo-score" => 1, "feedback-score" => 4.825, "ID" => null],
    ["year" => 2023, "month" => "July", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.820, "ID" => 2846],
    ["year" => 2023, "month" => "July", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.645, "ID" => null],
    ["year" => 2023, "month" => "July", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.640, "ID" => 9777],
    ["year" => 2023, "month" => "July", "db_name" => "LYNJE", "memo-score" => 3, "feedback-score" => 3.590, "ID" => null],

    ["year" => 2023, "month" => "August", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.840, "ID" => 2394],
    ["year" => 2023, "month" => "August", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2470],
    ["year" => 2023, "month" => "August", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 2856],
    ["year" => 2023, "month" => "August", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 7870],
    ["year" => 2023, "month" => "August", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.880, "ID" => null],
    ["year" => 2023, "month" => "August", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.790, "ID" => 2852],
    ["year" => 2023, "month" => "August", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11422],
    ["year" => 2023, "month" => "August", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 2858],
    ["year" => 2023, "month" => "August", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.500, "ID" => 9721],
    ["year" => 2023, "month" => "August", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 3002],
    ["year" => 2023, "month" => "August", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 10359],
    ["year" => 2023, "month" => "August", "db_name" => "ARLENE", "memo-score" => 3, "feedback-score" => 4.500, "ID" => 8059],
    ["year" => 2023, "month" => "August", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 4933],
    ["year" => 2023, "month" => "August", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "August", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 6379],
    ["year" => 2023, "month" => "August", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.730, "ID" => 2472],
    ["year" => 2023, "month" => "August", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 5561],
    ["year" => 2023, "month" => "August", "db_name" => "KEN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => null],
    ["year" => 2023, "month" => "August", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 4930],
    ["year" => 2023, "month" => "August", "db_name" => "ROMANO", "memo-score" => 5, "feedback-score" => 4.765, "ID" => null],
    ["year" => 2023, "month" => "August", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.605, "ID" => 2846],
    ["year" => 2023, "month" => "August", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.645, "ID" => null],
    ["year" => 2023, "month" => "August", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.700, "ID" => 9777],
    ["year" => 2023, "month" => "August", "db_name" => "LYNJE", "memo-score" => 5, "feedback-score" => 4.180, "ID" => null],

    ["year" => 2023, "month" => "September", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.865, "ID" => 2394],
    ["year" => 2023, "month" => "September", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.935, "ID" => 2470],
    ["year" => 2023, "month" => "September", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 2856],
    ["year" => 2023, "month" => "September", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 7870],
    ["year" => 2023, "month" => "September", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.825, "ID" => null],
    ["year" => 2023, "month" => "September", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2852],
    ["year" => 2023, "month" => "September", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11422],
    ["year" => 2023, "month" => "September", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2858],
    ["year" => 2023, "month" => "September", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 9721],
    ["year" => 2023, "month" => "September", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 3002],
    ["year" => 2023, "month" => "September", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 10359],
    ["year" => 2023, "month" => "September", "db_name" => "ARLENE", "memo-score" => 3, "feedback-score" => 4.880, "ID" => 8059],
    ["year" => 2023, "month" => "September", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 4933],
    ["year" => 2023, "month" => "September", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "September", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.515, "ID" => 6379],
    ["year" => 2023, "month" => "September", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 2472],
    ["year" => 2023, "month" => "September", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.863, "ID" => 5561],
    ["year" => 2023, "month" => "September", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.410, "ID" => 4930],
    ["year" => 2023, "month" => "September", "db_name" => "ROMANO", "memo-score" => 5, "feedback-score" => 4.705, "ID" => null],
    ["year" => 2023, "month" => "September", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.730, "ID" => 2846],
    ["year" => 2023, "month" => "September", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.765, "ID" => null],
    ["year" => 2023, "month" => "September", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 9777],
    ["year" => 2023, "month" => "September", "db_name" => "LYNJE", "memo-score" => 5, "feedback-score" => 4.355, "ID" => null],

    ["year" => 2023, "month" => "October", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.830, "ID" => 2394],
    ["year" => 2023, "month" => "October", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2470],
    ["year" => 2023, "month" => "October", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 2856],
    ["year" => 2023, "month" => "October", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 7870],
    ["year" => 2023, "month" => "October", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.750, "ID" => null],
    ["year" => 2023, "month" => "October", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 2852],
    ["year" => 2023, "month" => "October", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 11422],
    ["year" => 2023, "month" => "October", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 2858],
    ["year" => 2023, "month" => "October", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2023, "month" => "October", "db_name" => "JHUN", "memo-score" => 3, "feedback-score" => 4.935, "ID" => 3002],
    ["year" => 2023, "month" => "October", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 10359],
    ["year" => 2023, "month" => "October", "db_name" => "ARLENE", "memo-score" => 3, "feedback-score" => 4.500, "ID" => 8059],
    ["year" => 2023, "month" => "October", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 4933],
    ["year" => 2023, "month" => "October", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "October", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.685, "ID" => 6379],
    ["year" => 2023, "month" => "October", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.795, "ID" => 2472],
    ["year" => 2023, "month" => "October", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 5561],
    ["year" => 2023, "month" => "October", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.500, "ID" => 4930],
    ["year" => 2023, "month" => "October", "db_name" => "ROMANO", "memo-score" => 3, "feedback-score" => 4.940, "ID" => null],
    ["year" => 2023, "month" => "October", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.785, "ID" => 2846],
    ["year" => 2023, "month" => "October", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.815, "ID" => null],
    ["year" => 2023, "month" => "October", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 9777],
    ["year" => 2023, "month" => "October", "db_name" => "LYNJE", "memo-score" => 3, "feedback-score" => 5.000, "ID" => null],

    ["year" => 2023, "month" => "November", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.860, "ID" => 2394],
    ["year" => 2023, "month" => "November", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 2470],
    ["year" => 2023, "month" => "November", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2856],
    ["year" => 2023, "month" => "November", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 7870],
    ["year" => 2023, "month" => "November", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.735, "ID" => null],
    ["year" => 2023, "month" => "November", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2852],
    ["year" => 2023, "month" => "November", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11422],
    ["year" => 2023, "month" => "November", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2858],
    ["year" => 2023, "month" => "November", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.835, "ID" => 9721],
    ["year" => 2023, "month" => "November", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 3002],
    ["year" => 2023, "month" => "November", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.690, "ID" => 10359],
    ["year" => 2023, "month" => "November", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 8059],
    ["year" => 2023, "month" => "November", "db_name" => "DAISY", "memo-score" => 0, "feedback-score" => 0, "ID" => null],
    ["year" => 2023, "month" => "November", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 4933],
    ["year" => 2023, "month" => "November", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "November", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 6379],
    ["year" => 2023, "month" => "November", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.620, "ID" => 2472],
    ["year" => 2023, "month" => "November", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.855, "ID" => 5561],
    ["year" => 2023, "month" => "November", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 4930],
    ["year" => 2023, "month" => "November", "db_name" => "ROMANO", "memo-score" => 5, "feedback-score" => 4.885, "ID" => null],
    ["year" => 2023, "month" => "November", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.697, "ID" => 2846],
    ["year" => 2023, "month" => "November", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 5.000, "ID" => null],
    ["year" => 2023, "month" => "November", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 9777],

    ["year" => 2023, "month" => "December", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 2394],
    ["year" => 2023, "month" => "December", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.800, "ID" => 2470],
    ["year" => 2023, "month" => "December", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.910, "ID" => 2856],
    ["year" => 2023, "month" => "December", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2023, "month" => "December", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.910, "ID" => null],
    ["year" => 2023, "month" => "December", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.730, "ID" => 2852],
    ["year" => 2023, "month" => "December", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11422],
    ["year" => 2023, "month" => "December", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.600, "ID" => 2858],
    ["year" => 2023, "month" => "December", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2023, "month" => "December", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 3002],
    ["year" => 2023, "month" => "December", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.770, "ID" => 10359],
    ["year" => 2023, "month" => "December", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 8059],
    ["year" => 2023, "month" => "December", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2870],
    ["year" => 2023, "month" => "December", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 4933],
    ["year" => 2023, "month" => "December", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2023, "month" => "December", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.470, "ID" => 6379],
    ["year" => 2023, "month" => "December", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.860, "ID" => 2472],
    ["year" => 2023, "month" => "December", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.807, "ID" => 5561],
    ["year" => 2023, "month" => "December", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.580, "ID" => 4930],
    ["year" => 2023, "month" => "December", "db_name" => "ROMANO", "memo-score" => 5, "feedback-score" => 4.530, "ID" => 2846],
    ["year" => 2023, "month" => "December", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.535, "ID" => 2846],
    ["year" => 2023, "month" => "December", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.735, "ID" => null],
    ["year" => 2023, "month" => "December", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.765, "ID" => 9777],

    ["year" => 2024, "month" => "January", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.955, "ID" => 2394],
    ["year" => 2024, "month" => "January", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2470],
    ["year" => 2024, "month" => "January", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2856],
    ["year" => 2024, "month" => "January", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2024, "month" => "January", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.680, "ID" => null],
    ["year" => 2024, "month" => "January", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.375, "ID" => 2852],
    ["year" => 2024, "month" => "January", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11422],
    ["year" => 2024, "month" => "January", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2858],
    ["year" => 2024, "month" => "January", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2024, "month" => "January", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 3002],
    ["year" => 2024, "month" => "January", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.945, "ID" => 10359],
    ["year" => 2024, "month" => "January", "db_name" => "ARLENE", "memo-score" => 3, "feedback-score" => 4.880, "ID" => 8059],
    ["year" => 2024, "month" => "January", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2870],
    ["year" => 2024, "month" => "January", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 4933],
    ["year" => 2024, "month" => "January", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2024, "month" => "January", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.825, "ID" => 6379],
    ["year" => 2024, "month" => "January", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.475, "ID" => 2472],
    ["year" => 2024, "month" => "January", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.945, "ID" => 5561],
    ["year" => 2024, "month" => "January", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 4930],
    ["year" => 2024, "month" => "January", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.535, "ID" => 2846],
    ["year" => 2024, "month" => "January", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.675, "ID" => null],
    ["year" => 2024, "month" => "January", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.795, "ID" => 9777],

    ["year" => 2024, "month" => "February", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.830, "ID" => 2394],
    ["year" => 2024, "month" => "February", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2470],
    ["year" => 2024, "month" => "February", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 2856],
    ["year" => 2024, "month" => "February", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 7870],
    ["year" => 2024, "month" => "February", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.555, "ID" => null],
    ["year" => 2024, "month" => "February", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.430, "ID" => 2852],
    ["year" => 2024, "month" => "February", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.855, "ID" => 11422],
    ["year" => 2024, "month" => "February", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 2858],
    ["year" => 2024, "month" => "February", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 9721],
    ["year" => 2024, "month" => "February", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.865, "ID" => 3002],
    ["year" => 2024, "month" => "February", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 10359],
    ["year" => 2024, "month" => "February", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 8059],
    ["year" => 2024, "month" => "February", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2870],
    ["year" => 2024, "month" => "February", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.715, "ID" => 4933],
    ["year" => 2024, "month" => "February", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11421],
    ["year" => 2024, "month" => "February", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.705, "ID" => 6379],
    ["year" => 2024, "month" => "February", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.530, "ID" => 2472],
    ["year" => 2024, "month" => "February", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.795, "ID" => 5561],
    ["year" => 2024, "month" => "February", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.765, "ID" => 4930],
    ["year" => 2024, "month" => "February", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 2846],
    ["year" => 2024, "month" => "February", "db_name" => "JOHNCRIS", "memo-score" => 5, "feedback-score" => 4.880, "ID" => null],
    ["year" => 2024, "month" => "February", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 9777],

    ["year" => 2024, "month" => "March", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.785, "ID" => 2394],
    ["year" => 2024, "month" => "March", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2470],
    ["year" => 2024, "month" => "March", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2856],
    ["year" => 2024, "month" => "March", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 7870],
    ["year" => 2024, "month" => "March", "db_name" => "XANDER", "memo-score" => 5, "feedback-score" => 4.795, "ID" => null],
    ["year" => 2024, "month" => "March", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 2852],
    ["year" => 2024, "month" => "March", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11422],
    ["year" => 2024, "month" => "March", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.690, "ID" => 2858],
    ["year" => 2024, "month" => "March", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2024, "month" => "March", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 3002],
    ["year" => 2024, "month" => "March", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 10359],
    ["year" => 2024, "month" => "March", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 8059],
    ["year" => 2024, "month" => "March", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 2870],
    ["year" => 2024, "month" => "March", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 4933],
    ["year" => 2024, "month" => "March", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2024, "month" => "March", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.765, "ID" => 6379],
    ["year" => 2024, "month" => "March", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.475, "ID" => 2472],
    ["year" => 2024, "month" => "March", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.795, "ID" => 5561],
    ["year" => 2024, "month" => "March", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 4930],
    ["year" => 2024, "month" => "March", "db_name" => "DON", "memo-score" => 3, "feedback-score" => 4.670, "ID" => 2846],
    ["year" => 2024, "month" => "March", "db_name" => "JOHNCRIS", "memo-score" => 1, "feedback-score" => 4.675, "ID" => null],
    ["year" => 2024, "month" => "March", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 9777],

    ["year" => 2024, "month" => "April", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.785, "ID" => 2394],
    ["year" => 2024, "month" => "April", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 2470],
    ["year" => 2024, "month" => "April", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 2856],
    ["year" => 2024, "month" => "April", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2024, "month" => "April", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 2852],
    ["year" => 2024, "month" => "April", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 11422],
    ["year" => 2024, "month" => "April", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 2858],
    ["year" => 2024, "month" => "April", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2024, "month" => "April", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 3002],
    ["year" => 2024, "month" => "April", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 10359],
    ["year" => 2024, "month" => "April", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 8059],
    ["year" => 2024, "month" => "April", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 4.710, "ID" => 2870],
    ["year" => 2024, "month" => "April", "db_name" => "IVANN", "memo-score" => 3, "feedback-score" => 4.750, "ID" => 4933],
    ["year" => 2024, "month" => "April", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 11421],
    ["year" => 2024, "month" => "April", "db_name" => "MARIE", "memo-score" => 3, "feedback-score" => 4.680, "ID" => 6379],
    ["year" => 2024, "month" => "April", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.420, "ID" => 2472],
    ["year" => 2024, "month" => "April", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.590, "ID" => 5561],
    ["year" => 2024, "month" => "April", "db_name" => "DARWIN", "memo-score" => 3, "feedback-score" => 4.530, "ID" => 4930],
    ["year" => 2024, "month" => "April", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.395, "ID" => 2846],
    ["year" => 2024, "month" => "April", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 9777],

    ["year" => 2024, "month" => "May", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.900, "ID" => 2394],
    ["year" => 2024, "month" => "May", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2470],
    ["year" => 2024, "month" => "May", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2856],
    ["year" => 2024, "month" => "May", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2024, "month" => "May", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2852],
    ["year" => 2024, "month" => "May", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11422],
    ["year" => 2024, "month" => "May", "db_name" => "JOMAN", "memo-score" => 3, "feedback-score" => 4.875, "ID" => 2858],
    ["year" => 2024, "month" => "May", "db_name" => "CCUNANAN", "memo-score" => 3, "feedback-score" => 4.970, "ID" => 9721],
    ["year" => 2024, "month" => "May", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 3002],
    ["year" => 2024, "month" => "May", "db_name" => "CHRIS", "memo-score" => 3, "feedback-score" => 4.940, "ID" => 10359],
    ["year" => 2024, "month" => "May", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 8059],
    ["year" => 2024, "month" => "May", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2870],
    ["year" => 2024, "month" => "May", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 4933],
    ["year" => 2024, "month" => "May", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2024, "month" => "May", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 6379],
    ["year" => 2024, "month" => "May", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 4.660, "ID" => 2472],
    ["year" => 2024, "month" => "May", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 5561],
    ["year" => 2024, "month" => "May", "db_name" => "DARWIN", "memo-score" => 1, "feedback-score" => 5.000, "ID" => 4930],
    ["year" => 2024, "month" => "May", "db_name" => "DON", "memo-score" => 1, "feedback-score" => 4.730, "ID" => 2846],
    ["year" => 2024, "month" => "May", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 9777],


    ["year" => 2024, "month" => "June", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.650, "ID" => 2394],
    ["year" => 2024, "month" => "June", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.915, "ID" => 2470],
    ["year" => 2024, "month" => "June", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2856],
    ["year" => 2024, "month" => "June", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 7870],
    ["year" => 2024, "month" => "June", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.835, "ID" => 2852],
    ["year" => 2024, "month" => "June", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 11422],
    ["year" => 2024, "month" => "June", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.670, "ID" => 2858],
    ["year" => 2024, "month" => "June", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.735, "ID" => 9721],
    ["year" => 2024, "month" => "June", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.585, "ID" => 3002],
    ["year" => 2024, "month" => "June", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 10359],
    ["year" => 2024, "month" => "June", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.920, "ID" => 8059],
    ["year" => 2024, "month" => "June", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2870],
    ["year" => 2024, "month" => "June", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 4933],
    ["year" => 2024, "month" => "June", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2024, "month" => "June", "db_name" => "MARIE", "memo-score" => 3, "feedback-score" => 5.000, "ID" => 6379],
    ["year" => 2024, "month" => "June", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 4.300, "ID" => 2472],
    ["year" => 2024, "month" => "June", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.845, "ID" => 5561],
    ["year" => 2024, "month" => "June", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.760, "ID" => 4930],
    ["year" => 2024, "month" => "June", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.670, "ID" => 2846],
    ["year" => 2024, "month" => "June", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.770, "ID" => 9777],


    ["year" => 2024, "month" => "July", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 4.765, "ID" => 2394],
    ["year" => 2024, "month" => "July", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2470],
    ["year" => 2024, "month" => "July", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2856],
    ["year" => 2024, "month" => "July", "db_name" => "RUFFY", "memo-score" => 3, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2024, "month" => "July", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2852],
    ["year" => 2024, "month" => "July", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 11422],
    ["year" => 2024, "month" => "July", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.815, "ID" => 2858],
    ["year" => 2024, "month" => "July", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2024, "month" => "July", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 3002],
    ["year" => 2024, "month" => "July", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 10359],
    ["year" => 2024, "month" => "July", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 8059],
    ["year" => 2024, "month" => "July", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2870],
    ["year" => 2024, "month" => "July", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 4933],
    ["year" => 2024, "month" => "July", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2024, "month" => "July", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.560, "ID" => 6379],
    ["year" => 2024, "month" => "July", "db_name" => "BRY", "memo-score" => 5, "feedback-score" => 4.335, "ID" => 2472],
    ["year" => 2024, "month" => "July", "db_name" => "PJ", "memo-score" => 5, "feedback-score" => 4.705, "ID" => 5561],
    ["year" => 2024, "month" => "July", "db_name" => "DARWIN", "memo-score" => 3, "feedback-score" => 4.530, "ID" => 4930],
    ["year" => 2024, "month" => "July", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.525, "ID" => 2846],
    ["year" => 2024, "month" => "July", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.825, "ID" => 9777],


    ["year" => 2024, "month" => "August", "db_name" => "RUSTAN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2394],
    ["year" => 2024, "month" => "August", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2470],
    ["year" => 2024, "month" => "August", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2856],
    ["year" => 2024, "month" => "August", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.970, "ID" => 7870],
    ["year" => 2024, "month" => "August", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2852],
    ["year" => 2024, "month" => "August", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.910, "ID" => 11422],
    ["year" => 2024, "month" => "August", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.500, "ID" => 2858],
    ["year" => 2024, "month" => "August", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.795, "ID" => 9721],
    ["year" => 2024, "month" => "August", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 3002],
    ["year" => 2024, "month" => "August", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 10359],
    ["year" => 2024, "month" => "August", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 8059],
    ["year" => 2024, "month" => "August", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 2870],
    ["year" => 2024, "month" => "August", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 4933],
    ["year" => 2024, "month" => "August", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2024, "month" => "August", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.765, "ID" => 6379],
    ["year" => 2024, "month" => "August", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 4.500, "ID" => 2472],
    ["year" => 2024, "month" => "August", "db_name" => "PJ", "memo-score" => 3, "feedback-score" => 4.710, "ID" => 5561],
    ["year" => 2024, "month" => "August", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.710, "ID" => 4930],
    ["year" => 2024, "month" => "August", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.500, "ID" => 2846],
    ["year" => 2024, "month" => "August", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.885, "ID" => 9777],

    ["year" => 2024, "month" => "September", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.938, "ID" => 2470],
    ["year" => 2024, "month" => "September", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 2856],
    ["year" => 2024, "month" => "September", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 7870],
    ["year" => 2024, "month" => "September", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 4.590, "ID" => 2852],
    ["year" => 2024, "month" => "September", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 11422],
    ["year" => 2024, "month" => "September", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 2858],
    ["year" => 2024, "month" => "September", "db_name" => "CCUNANAN", "memo-score" => 3, "feedback-score" => 5.000, "ID" => 9721],
    ["year" => 2024, "month" => "September", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 3002],
    ["year" => 2024, "month" => "September", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 10359],
    ["year" => 2024, "month" => "September", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.625, "ID" => 8059],
    ["year" => 2024, "month" => "September", "db_name" => "DAISY", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2870],
    ["year" => 2024, "month" => "September", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 4933],
    ["year" => 2024, "month" => "September", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2024, "month" => "September", "db_name" => "MARIE", "memo-score" => 5, "feedback-score" => 4.675, "ID" => 6379],
    ["year" => 2024, "month" => "September", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 4.465, "ID" => 2472],
    ["year" => 2024, "month" => "September", "db_name" => "PJ", "memo-score" => 3, "feedback-score" => 4.790, "ID" => 5561],
    ["year" => 2024, "month" => "September", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.470, "ID" => 4930],
    ["year" => 2024, "month" => "September", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.530, "ID" => 2846],
    ["year" => 2024, "month" => "September", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 9777],

    ["year" => 2024, "month" => "October", "db_name" => "RUSTAN", "memo-score" => 3, "feedback-score" => 4.780, "ID" => 2394],
    ["year" => 2024, "month" => "October", "db_name" => "SALLY", "memo-score" => 5, "feedback-score" => 4.750, "ID" => 2470],
    ["year" => 2024, "month" => "October", "db_name" => "NEL", "memo-score" => 5, "feedback-score" => 4.970, "ID" => 2856],
    ["year" => 2024, "month" => "October", "db_name" => "RUFFY", "memo-score" => 5, "feedback-score" => 4.970, "ID" => 7870],
    ["year" => 2024, "month" => "October", "db_name" => "MHEL", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 2852],
    ["year" => 2024, "month" => "October", "db_name" => "RANDY", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 11422],
    ["year" => 2024, "month" => "October", "db_name" => "JOMAN", "memo-score" => 5, "feedback-score" => 4.625, "ID" => 2858],
    ["year" => 2024, "month" => "October", "db_name" => "CCUNANAN", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 9721],
    ["year" => 2024, "month" => "October", "db_name" => "JHUN", "memo-score" => 5, "feedback-score" => 4.875, "ID" => 3002],
    ["year" => 2024, "month" => "October", "db_name" => "CHRIS", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 10359],
    ["year" => 2024, "month" => "October", "db_name" => "ARLENE", "memo-score" => 5, "feedback-score" => 4.810, "ID" => 8059],
    ["year" => 2024, "month" => "October", "db_name" => "DAISY", "memo-score" => 3, "feedback-score" => 4.795, "ID" => 2870],
    ["year" => 2024, "month" => "October", "db_name" => "IVANN", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 4933],
    ["year" => 2024, "month" => "October", "db_name" => "MACEDO", "memo-score" => 5, "feedback-score" => 5.000, "ID" => 11421],
    ["year" => 2024, "month" => "October", "db_name" => "MARIE", "memo-score" => 3, "feedback-score" => 5.000, "ID" => 6379],
    ["year" => 2024, "month" => "October", "db_name" => "BRY", "memo-score" => 3, "feedback-score" => 4.305, "ID" => 2472],
    ["year" => 2024, "month" => "October", "db_name" => "PJ", "memo-score" => 1, "feedback-score" => 4.820, "ID" => 5561],
    ["year" => 2024, "month" => "October", "db_name" => "DARWIN", "memo-score" => 5, "feedback-score" => 4.880, "ID" => 4930],
    ["year" => 2024, "month" => "October", "db_name" => "DON", "memo-score" => 5, "feedback-score" => 4.520, "ID" => 2846],
    ["year" => 2024, "month" => "October", "db_name" => "VINCENT", "memo-score" => 5, "feedback-score" => 4.940, "ID" => 9777]
];


    // Helper function to get a random date within a month and year
function getRandomDate($month, $year) {
    $startDate = "$year-$month-01";
    $endDate = date("Y-m-t", strtotime($startDate));
    return date("Y-m-d", mt_rand(strtotime($startDate), strtotime($endDate)));
}

foreach ($data as $row) {
    $agent_id = $row['ID'];
    $month = $row['month'];
    $year = $row['year'];
    $memo_score = $row['memo-score'];
    $feedback_score =$row['feedback-score'];

    // Determine the number of entries to insert
    $memo_to_insert = 0;
    if ($memo_score == 3) {
        $memo_to_insert = 1;
    } elseif ($memo_score == 1) {
        $memo_to_insert = 2;
    } elseif ($memo_score == 0) {
        $memo_to_insert = 3;
    }

    if ($agent_id == null){
        echo "Dont add this records";
        continue;
    }else {
            // Insert into memo table
    for ($i = 1; $i <= $memo_to_insert; $i++) {

        //Dont insert anythin if  the memo_score = 5
        if ($memo_score == 5 ){
          echo "$agent_id". " has no memo ";
                continue;
        }
        $random_date = getRandomDate(date("m", strtotime($month)), $year);
        $description = ($i == 1) ? "First memo" : (($i == 2) ? "Second memo" : "Third memo");
        
      
        $sql = "INSERT INTO memo (agent_id, month, year, date, description)
                VALUES ('$agent_id', '$month', '$year', '$random_date', '$description')";

        if ($conn->query($sql) === TRUE) {
            echo "New record created successfully for agent_id $agent_id\n";
        } else {
            echo "Error: " . $sql . "\n" . $conn->error;
        }
    }

        //Insert into Feedback table
        $random_date = getRandomDate(date("m", strtotime($month)), $year);
        $sql = "INSERT INTO feedback (agent_id, month, year, date, feedback)
                VALUES ('$agent_id', '$month', '$year', '$random_date', '$feedback_score')";

        if ($conn->query($sql) === TRUE) {
            echo "New record created successfully for agent_id $agent_id\n";
        } else {
            echo "Error: " . $sql . "\n" . $conn->error;
        }
    }



}

$conn->close();
?>
