<?php
$servername = "localhost";
$username = "python";
$password = "sbtph@2018";
$dbname = "sbtph_leaderboard"; // Replace with your database name

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Data array

$data = [
    ['year' => 2023, 'month' => 'January', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'SALLY', 'newdeposit_score' => 0, 'ID' => 2470],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'NEL', 'newdeposit_score' => 1, 'ID' => 2856],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'RUFFY', 'newdeposit_score' => 0, 'ID' => 7870],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'CHRIS', 'newdeposit_score' => 0, 'ID' => 10359],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'KATHY', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 0, 'ID' => 9721],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'ARLENE', 'newdeposit_score' => 0, 'ID' => 8059],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'EZEKIEL', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'XANDER', 'newdeposit_score' => 0, 'ID' => 4933],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'IVANN', 'newdeposit_score' => 0, 'ID' => 4933],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'MACEDO', 'newdeposit_score' => 1, 'ID' => 11421],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'PJ', 'newdeposit_score' => 0, 'ID' => 5561],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'KEN', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'DARWIN', 'newdeposit_score' => 1, 'ID' => 4930],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'VINCENT', 'newdeposit_score' => 1, 'ID' => 9777],
    ['year' => 2023, 'month' => 'January', 'db_name' => 'ROMANO', 'newdeposit_score' => 0, 'ID' => null],
    // February Data
    ['year' => 2023, 'month' => 'February', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'SALLY', 'newdeposit_score' => 0, 'ID' => 2470],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'NEL', 'newdeposit_score' => 2, 'ID' => 2856],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'RUFFY', 'newdeposit_score' => 3, 'ID' => 7870],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'CHRIS', 'newdeposit_score' => 0, 'ID' => 10359],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'KATHY', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 0, 'ID' => 9721],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'ARLENE', 'newdeposit_score' => 0, 'ID' => 8059],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'EZEKIEL', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'XANDER', 'newdeposit_score' => 0, 'ID' => 4933],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'IVANN', 'newdeposit_score' => 1, 'ID' => 4933],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'MACEDO', 'newdeposit_score' => 3, 'ID' => 11421],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'PJ', 'newdeposit_score' => 0, 'ID' => 5561],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'KEN', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'DARWIN', 'newdeposit_score' => 0, 'ID' => 4930],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'DON', 'newdeposit_score' => 1, 'ID' => 2846],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'VINCENT', 'newdeposit_score' => 3, 'ID' => 9777],
    ['year' => 2023, 'month' => 'February', 'db_name' => 'ROMANO', 'newdeposit_score' => 0, 'ID' => null],
    // March Data
    ['year' => 2023, 'month' => 'March', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'SALLY', 'newdeposit_score' => 1, 'ID' => 2470],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'NEL', 'newdeposit_score' => 3, 'ID' => 2856],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'RUFFY', 'newdeposit_score' => 0, 'ID' => 7870],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'MHEL', 'newdeposit_score' => 1, 'ID' => 2852],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'JHUN', 'newdeposit_score' => 1, 'ID' => 3002],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'CHRIS', 'newdeposit_score' => 1, 'ID' => 10359],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'KATHY', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 0, 'ID' => 9721],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'ARLENE', 'newdeposit_score' => 1, 'ID' => 8059],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'EZEKIEL', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'XANDER', 'newdeposit_score' => 0, 'ID' => 4933],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'IVANN', 'newdeposit_score' => 0, 'ID' => 4933],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'MACEDO', 'newdeposit_score' => 2, 'ID' => 11421],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'BRY', 'newdeposit_score' => 1, 'ID' => 2472],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'PJ', 'newdeposit_score' => 1, 'ID' => 5561],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'KEN', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'DARWIN', 'newdeposit_score' => 0, 'ID' => 4930],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'VINCENT', 'newdeposit_score' => 1, 'ID' => 9777],
    ['year' => 2023, 'month' => 'March', 'db_name' => 'ROMANO', 'newdeposit_score' => 0, 'ID' => null],
    // April Data
    ['year' => 2023, 'month' => 'April', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'SALLY', 'newdeposit_score' => 1, 'ID' => 2470],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'NEL', 'newdeposit_score' => 1, 'ID' => 2856],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'RUFFY', 'newdeposit_score' => 0, 'ID' => 7870],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'CHRIS', 'newdeposit_score' => 1, 'ID' => 10359],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'KATHY', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 0, 'ID' => 9721],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'ARLENE', 'newdeposit_score' => 0, 'ID' => 8059],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'EZEKIEL', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'XANDER', 'newdeposit_score' => 0, 'ID' => 4933],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'IVANN', 'newdeposit_score' => 1, 'ID' => 4933],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'MACEDO', 'newdeposit_score' => 0, 'ID' => 11421],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'BRY', 'newdeposit_score' => 1, 'ID' => 2472],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'PJ', 'newdeposit_score' => 1, 'ID' => 5561],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'KEN', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'DARWIN', 'newdeposit_score' => 0, 'ID' => 4930],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 0, 'ID' => null],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'VINCENT', 'newdeposit_score' => 0, 'ID' => 9777],
    ['year' => 2023, 'month' => 'April', 'db_name' => 'ROMANO', 'newdeposit_score' => 0, 'ID' => null],

    ['year' => 2023, 'month' => 'May', 'db_name' => 'RUSTAN', 'newdeposit_score' => 2, 'ID' => 2394],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'SALLY', 'newdeposit_score' => 1, 'ID' => 2470],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'NEL', 'newdeposit_score' => 3, 'ID' => 2856],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'RUFFY', 'newdeposit_score' => 0, 'ID' => 7870],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'MHEL', 'newdeposit_score' => 2, 'ID' => 2852],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'RANDY', 'newdeposit_score' => 1, 'ID' => 11422],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'JOMAN', 'newdeposit_score' => 4, 'ID' => 2858],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 2, 'ID' => 9721],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'CHRIS', 'newdeposit_score' => 1, 'ID' => 10359],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'ARLENE', 'newdeposit_score' => 3, 'ID' => 8059],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'DAISY', 'newdeposit_score' => 0, 'ID' => 2870],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'IVANN', 'newdeposit_score' => 1, 'ID' => 4933],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'MACEDO', 'newdeposit_score' => 2, 'ID' => 11421],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'MARIE', 'newdeposit_score' => 1, 'ID' => 6379],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'PJ', 'newdeposit_score' => 3, 'ID' => 5561],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'DARWIN', 'newdeposit_score' => 4, 'ID' => 4930],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'DON', 'newdeposit_score' => 1, 'ID' => 2846],
    ['year' => 2023, 'month' => 'May', 'db_name' => 'VINCENT', 'newdeposit_score' => 2, 'ID' => 9777],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'RUSTAN', 'newdeposit_score' => 3, 'ID' => 2394],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'SALLY', 'newdeposit_score' => 1, 'ID' => 2470],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'NEL', 'newdeposit_score' => 0, 'ID' => 2856],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'RUFFY', 'newdeposit_score' => 2, 'ID' => 7870],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'MHEL', 'newdeposit_score' => 4, 'ID' => 2852],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'RANDY', 'newdeposit_score' => 2, 'ID' => 11422],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'JOMAN', 'newdeposit_score' => 3, 'ID' => 2858],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'CHRIS', 'newdeposit_score' => 4, 'ID' => 10359],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'ARLENE', 'newdeposit_score' => 1, 'ID' => 8059],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'DAISY', 'newdeposit_score' => 3, 'ID' => 2870],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'IVANN', 'newdeposit_score' => 2, 'ID' => 4933],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'MACEDO', 'newdeposit_score' => 1, 'ID' => 11421],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'PJ', 'newdeposit_score' => 4, 'ID' => 5561],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'DARWIN', 'newdeposit_score' => 3, 'ID' => 4930],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'DON', 'newdeposit_score' => 1, 'ID' => 2846],
    ['year' => 2023, 'month' => 'June', 'db_name' => 'VINCENT', 'newdeposit_score' => 5, 'ID' => 9777],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'RUSTAN', 'newdeposit_score' => 2, 'ID' => 2394],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'SALLY', 'newdeposit_score' => 3, 'ID' => 2470],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'NEL', 'newdeposit_score' => 1, 'ID' => 2856],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'RUFFY', 'newdeposit_score' => 2, 'ID' => 7870],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'MHEL', 'newdeposit_score' => 1, 'ID' => 2852],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'RANDY', 'newdeposit_score' => 4, 'ID' => 11422],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'JOMAN', 'newdeposit_score' => 3, 'ID' => 2858],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 2, 'ID' => 9721],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'JHUN', 'newdeposit_score' => 3, 'ID' => 3002],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'CHRIS', 'newdeposit_score' => 2, 'ID' => 10359],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'ARLENE', 'newdeposit_score' => 1, 'ID' => 8059],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'DAISY', 'newdeposit_score' => 3, 'ID' => 2870],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'IVANN', 'newdeposit_score' => 2, 'ID' => 4933],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'MACEDO', 'newdeposit_score' => 1, 'ID' => 11421],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'BRY', 'newdeposit_score' => 4, 'ID' => 2472],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'PJ', 'newdeposit_score' => 0, 'ID' => 5561],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'DARWIN', 'newdeposit_score' => 1, 'ID' => 4930],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'DON', 'newdeposit_score' => 2, 'ID' => 2846],
    ['year' => 2023, 'month' => 'July', 'db_name' => 'VINCENT', 'newdeposit_score' => 3, 'ID' => 9777],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'RUSTAN', 'newdeposit_score' => 4, 'ID' => 2394],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'SALLY', 'newdeposit_score' => 1, 'ID' => 2470],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'NEL', 'newdeposit_score' => 3, 'ID' => 2856],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'RUFFY', 'newdeposit_score' => 2, 'ID' => 7870],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'MHEL', 'newdeposit_score' => 1, 'ID' => 2852],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'JOMAN', 'newdeposit_score' => 4, 'ID' => 2858],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 2, 'ID' => 9721],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'JHUN', 'newdeposit_score' => 1, 'ID' => 3002],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'CHRIS', 'newdeposit_score' => 0, 'ID' => 10359],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'ARLENE', 'newdeposit_score' => 2, 'ID' => 8059],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'DAISY', 'newdeposit_score' => 4, 'ID' => 2870],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'IVANN', 'newdeposit_score' => 0, 'ID' => 4933],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'MACEDO', 'newdeposit_score' => 1, 'ID' => 11421],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'BRY', 'newdeposit_score' => 3, 'ID' => 2472],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'PJ', 'newdeposit_score' => 4, 'ID' => 5561],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'DARWIN', 'newdeposit_score' => 3, 'ID' => 4930],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'DON', 'newdeposit_score' => 1, 'ID' => 2846],
    ['year' => 2023, 'month' => 'August', 'db_name' => 'VINCENT', 'newdeposit_score' => 2, 'ID' => 9777],

 
    ['year' => 2023, 'month' => 'September', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'SALLY', 'newdeposit_score' => null, 'ID' => 2470],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'NEL', 'newdeposit_score' => 1, 'ID' => 2856],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'RUFFY', 'newdeposit_score' => 8, 'ID' => 7870],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'XANDER', 'newdeposit_score' => null, 'ID' => null],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'RANDY', 'newdeposit_score' => 2, 'ID' => 11422],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'CHRIS', 'newdeposit_score' => null, 'ID' => 10359],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'ARLENE', 'newdeposit_score' => 2, 'ID' => 8059],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'IVANN', 'newdeposit_score' => null, 'ID' => 4933],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'MACEDO', 'newdeposit_score' => 4, 'ID' => 11421],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'MARIE', 'newdeposit_score' => 4, 'ID' => 6379],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'PJ', 'newdeposit_score' => 1, 'ID' => 5561],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'DARWIN', 'newdeposit_score' => 3, 'ID' => 4930],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'ROMANO', 'newdeposit_score' => 3, 'ID' => null],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'DON', 'newdeposit_score' => 1, 'ID' => 2846],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 2, 'ID' => null],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'VINCENT', 'newdeposit_score' => 2, 'ID' => 9777],
    ['year' => 2023, 'month' => 'September', 'db_name' => 'LYNJE', 'newdeposit_score' => 1, 'ID' => null],

    ['year' => 2023, 'month' => 'October', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'SALLY', 'newdeposit_score' => null, 'ID' => 2470],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'NEL', 'newdeposit_score' => null, 'ID' => 2856],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'RUFFY', 'newdeposit_score' => 4, 'ID' => 7870],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'XANDER', 'newdeposit_score' => null, 'ID' => null],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'RANDY', 'newdeposit_score' => 1, 'ID' => 11422],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'JOMAN', 'newdeposit_score' => 1, 'ID' => 2858],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'CHRIS', 'newdeposit_score' => 2, 'ID' => 10359],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'ARLENE', 'newdeposit_score' => 6, 'ID' => 8059],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'IVANN', 'newdeposit_score' => null, 'ID' => 4933],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'MACEDO', 'newdeposit_score' => 6, 'ID' => 11421],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'MARIE', 'newdeposit_score' => 4, 'ID' => 6379],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'PJ', 'newdeposit_score' => 2, 'ID' => 5561],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'DARWIN', 'newdeposit_score' => 3, 'ID' => 4930],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'ROMANO', 'newdeposit_score' => 2, 'ID' => null],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => null, 'ID' => null],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'VINCENT', 'newdeposit_score' => 1, 'ID' => 9777],
    ['year' => 2023, 'month' => 'October', 'db_name' => 'LYNJE', 'newdeposit_score' => null, 'ID' => null],
    

     // November 2023
     ['year' => 2023, 'month' => 'November', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'SALLY', 'newdeposit_score' => null, 'ID' => 2470],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'NEL', 'newdeposit_score' => 2.00, 'ID' => 2856],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'RUFFY', 'newdeposit_score' => 1.00, 'ID' => 7870],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'XANDER', 'newdeposit_score' => 2.00, 'ID' => 2857],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'RANDY', 'newdeposit_score' => 2.00, 'ID' => 11422],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'CCUNANAN', 'newdeposit_score' => null, 'ID' => 9721],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'CHRIS', 'newdeposit_score' => 1.00, 'ID' => 10359],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'ARLENE', 'newdeposit_score' => 4.00, 'ID' => 8059],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'DAISY', 'newdeposit_score' => null, 'ID' => 2870],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'IVANN', 'newdeposit_score' => null, 'ID' => 4933],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'MACEDO', 'newdeposit_score' => 5.00, 'ID' => 11421],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'MARIE', 'newdeposit_score' => 5.00, 'ID' => 6379],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'PJ', 'newdeposit_score' => null, 'ID' => 5561],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'DARWIN', 'newdeposit_score' => 1.00, 'ID' => 4930],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'ROMANO', 'newdeposit_score' => null, 'ID' => 7854],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 1.00, 'ID' => 1292],
     ['year' => 2023, 'month' => 'November', 'db_name' => 'VINCENT', 'newdeposit_score' => 2.00, 'ID' => 9777],
 
     // December 2023
     ['year' => 2023, 'month' => 'December', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'SALLY', 'newdeposit_score' => null, 'ID' => 2470],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'NEL', 'newdeposit_score' => 1.00, 'ID' => 2856],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'RUFFY', 'newdeposit_score' => 3.00, 'ID' => 7870],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'XANDER', 'newdeposit_score' => 1.00, 'ID' => 2857],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'RANDY', 'newdeposit_score' => 1.00, 'ID' => 11422],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'CCUNANAN', 'newdeposit_score' => null, 'ID' => 9721],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'CHRIS', 'newdeposit_score' => null, 'ID' => 10359],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'ARLENE', 'newdeposit_score' => 1.00, 'ID' => 8059],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'DAISY', 'newdeposit_score' => 3.00, 'ID' => 2870],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'IVANN', 'newdeposit_score' => null, 'ID' => 4933],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'MACEDO', 'newdeposit_score' => 6.00, 'ID' => 11421],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'MARIE', 'newdeposit_score' => 5.00, 'ID' => 6379],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'PJ', 'newdeposit_score' => null, 'ID' => 5561],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'DARWIN', 'newdeposit_score' => 1.00, 'ID' => 4930],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'ROMANO', 'newdeposit_score' => 1.00, 'ID' => 7854],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => null, 'ID' => 1292],
     ['year' => 2023, 'month' => 'December', 'db_name' => 'VINCENT', 'newdeposit_score' => 1.00, 'ID' => 9777],



        // January
    ['year' => 2024, 'month' => 'January', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'SALLY', 'newdeposit_score' => 0, 'ID' => 2470],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'NEL', 'newdeposit_score' => 1, 'ID' => 2856],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'RUFFY', 'newdeposit_score' => 2, 'ID' => 7870],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'XANDER', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'CHRIS', 'newdeposit_score' => 0, 'ID' => 10359],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'ARLENE', 'newdeposit_score' => 0, 'ID' => 8059],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'DAISY', 'newdeposit_score' => 2, 'ID' => 2870],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'IVANN', 'newdeposit_score' => 1, 'ID' => 4933],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'MACEDO', 'newdeposit_score' => 3, 'ID' => 11421],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'PJ', 'newdeposit_score' => 0, 'ID' => 5561],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'DARWIN', 'newdeposit_score' => 2, 'ID' => 4930],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 2, 'ID' => 1616],
    ['year' => 2024, 'month' => 'January', 'db_name' => 'VINCENT', 'newdeposit_score' => 0, 'ID' => 9777],

    // February
    ['year' => 2024, 'month' => 'February', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'SALLY', 'newdeposit_score' => 0, 'ID' => 2470],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'NEL', 'newdeposit_score' => 1, 'ID' => 2856],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'RUFFY', 'newdeposit_score' => 2, 'ID' => 7870],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'XANDER', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'CHRIS', 'newdeposit_score' => 0, 'ID' => 10359],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'ARLENE', 'newdeposit_score' => 0, 'ID' => 8059],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'DAISY', 'newdeposit_score' => 2, 'ID' => 2870],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'IVANN', 'newdeposit_score' => 1, 'ID' => 4933],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'MACEDO', 'newdeposit_score' => 3, 'ID' => 11421],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'PJ', 'newdeposit_score' => 0, 'ID' => 5561],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'DARWIN', 'newdeposit_score' => 2, 'ID' => 4930],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 2, 'ID' => 1616],
    ['year' => 2024, 'month' => 'February', 'db_name' => 'VINCENT', 'newdeposit_score' => 0, 'ID' => 9777],

    // March
    ['year' => 2024, 'month' => 'March', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'SALLY', 'newdeposit_score' => 0, 'ID' => 2470],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'NEL', 'newdeposit_score' => 1, 'ID' => 2856],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'RUFFY', 'newdeposit_score' => 2, 'ID' => 7870],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'XANDER', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'CHRIS', 'newdeposit_score' => 0, 'ID' => 10359],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'ARLENE', 'newdeposit_score' => 0, 'ID' => 8059],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'DAISY', 'newdeposit_score' => 2, 'ID' => 2870],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'IVANN', 'newdeposit_score' => 1, 'ID' => 4933],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'MACEDO', 'newdeposit_score' => 3, 'ID' => 11421],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'PJ', 'newdeposit_score' => 0, 'ID' => 5561],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'DARWIN', 'newdeposit_score' => 2, 'ID' => 4930],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 2, 'ID' => 1616],
    ['year' => 2024, 'month' => 'March', 'db_name' => 'VINCENT', 'newdeposit_score' => 0, 'ID' => 9777],

    // April
    ['year' => 2024, 'month' => 'April', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'SALLY', 'newdeposit_score' => 0, 'ID' => 2470],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'NEL', 'newdeposit_score' => 1, 'ID' => 2856],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'RUFFY', 'newdeposit_score' => 2, 'ID' => 7870],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'XANDER', 'newdeposit_score' => 1, 'ID' => null],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'CHRIS', 'newdeposit_score' => 0, 'ID' => 10359],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'ARLENE', 'newdeposit_score' => 0, 'ID' => 8059],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'DAISY', 'newdeposit_score' => 2, 'ID' => 2870],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'IVANN', 'newdeposit_score' => 1, 'ID' => 4933],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'MACEDO', 'newdeposit_score' => 3, 'ID' => 11421],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'PJ', 'newdeposit_score' => 0, 'ID' => 5561],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'DARWIN', 'newdeposit_score' => 2, 'ID' => 4930],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'JOHNCRIS', 'newdeposit_score' => 2, 'ID' => 1616],
    ['year' => 2024, 'month' => 'April', 'db_name' => 'VINCENT', 'newdeposit_score' => 0, 'ID' => 9777],

    ['year' => 2024, 'month' => 'May', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'SALLY', 'newdeposit_score' => null, 'ID' => 2470],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'NEL', 'newdeposit_score' => null, 'ID' => 2856],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'RUFFY', 'newdeposit_score' => 4, 'ID' => 7870],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'RANDY', 'newdeposit_score' => null, 'ID' => 11422],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'CCUNANAN', 'newdeposit_score' => null, 'ID' => 9721],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'CHRIS', 'newdeposit_score' => 3, 'ID' => 10359],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'ARLENE', 'newdeposit_score' => null, 'ID' => 8059],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'DAISY', 'newdeposit_score' => 4, 'ID' => 2870],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'IVANN', 'newdeposit_score' => null, 'ID' => 4933],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'MACEDO', 'newdeposit_score' => 4, 'ID' => 11421],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'MARIE', 'newdeposit_score' => 4, 'ID' => 6379],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'PJ', 'newdeposit_score' => null, 'ID' => 5561],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'DARWIN', 'newdeposit_score' => 2, 'ID' => 4930],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
    ['year' => 2024, 'month' => 'May', 'db_name' => 'VINCENT', 'newdeposit_score' => 2, 'ID' => 9777],

    ['year' => 2024, 'month' => 'June', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'SALLY', 'newdeposit_score' => null, 'ID' => 2470],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'NEL', 'newdeposit_score' => null, 'ID' => 2856],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'RUFFY', 'newdeposit_score' => 1, 'ID' => 7870],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'RANDY', 'newdeposit_score' => null, 'ID' => 11422],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'CCUNANAN', 'newdeposit_score' => null, 'ID' => 9721],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'CHRIS', 'newdeposit_score' => null, 'ID' => 10359],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'ARLENE', 'newdeposit_score' => null, 'ID' => 8059],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'DAISY', 'newdeposit_score' => 4, 'ID' => 2870],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'IVANN', 'newdeposit_score' => 1, 'ID' => 4933],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'MACEDO', 'newdeposit_score' => 3, 'ID' => 11421],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'MARIE', 'newdeposit_score' => 3, 'ID' => 6379],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'PJ', 'newdeposit_score' => null, 'ID' => 5561],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'DARWIN', 'newdeposit_score' => null, 'ID' => 4930],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
    ['year' => 2024, 'month' => 'June', 'db_name' => 'VINCENT', 'newdeposit_score' => 1, 'ID' => 9777],

    ['year' => 2024, 'month' => 'July', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'SALLY', 'newdeposit_score' => 1, 'ID' => 2470],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'NEL', 'newdeposit_score' => null, 'ID' => 2856],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'RUFFY', 'newdeposit_score' => 4, 'ID' => 7870],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'RANDY', 'newdeposit_score' => null, 'ID' => 11422],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'CCUNANAN', 'newdeposit_score' => null, 'ID' => 9721],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'CHRIS', 'newdeposit_score' => 2, 'ID' => 10359],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'ARLENE', 'newdeposit_score' => null, 'ID' => 8059],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'DAISY', 'newdeposit_score' => null, 'ID' => 2870],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'IVANN', 'newdeposit_score' => null, 'ID' => 4933],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'MACEDO', 'newdeposit_score' => null, 'ID' => 11421],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'MARIE', 'newdeposit_score' => null, 'ID' => 6379],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'PJ', 'newdeposit_score' => null, 'ID' => 5561],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'DARWIN', 'newdeposit_score' => null, 'ID' => 4930],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
    ['year' => 2024, 'month' => 'July', 'db_name' => 'VINCENT', 'newdeposit_score' => null, 'ID' => 9777],

    ['year' => 2024, 'month' => 'August', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'SALLY', 'newdeposit_score' => null, 'ID' => 2470],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'NEL', 'newdeposit_score' => null, 'ID' => 2856],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'RUFFY', 'newdeposit_score' => null, 'ID' => 7870],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'RANDY', 'newdeposit_score' => null, 'ID' => 11422],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'CCUNANAN', 'newdeposit_score' => null, 'ID' => 9721],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'CHRIS', 'newdeposit_score' => null, 'ID' => 10359],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'ARLENE', 'newdeposit_score' => null, 'ID' => 8059],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'DAISY', 'newdeposit_score' => null, 'ID' => 2870],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'IVANN', 'newdeposit_score' => null, 'ID' => 4933],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'MACEDO', 'newdeposit_score' => null, 'ID' => 11421],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'MARIE', 'newdeposit_score' => null, 'ID' => 6379],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'PJ', 'newdeposit_score' => null, 'ID' => 5561],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'DARWIN', 'newdeposit_score' => null, 'ID' => 4930],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
    ['year' => 2024, 'month' => 'August', 'db_name' => 'VINCENT', 'newdeposit_score' => null, 'ID' => 9777],

    ['year' => 2024, 'month' => 'September', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'SALLY', 'newdeposit_score' => 1, 'ID' => 2470],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'NEL', 'newdeposit_score' => null, 'ID' => 2856],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'RUFFY', 'newdeposit_score' => null, 'ID' => 7870],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'RANDY', 'newdeposit_score' => null, 'ID' => 11422],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'JHUN', 'newdeposit_score' => 1, 'ID' => 3002],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'CHRIS', 'newdeposit_score' => 1, 'ID' => 10359],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'ARLENE', 'newdeposit_score' => 1, 'ID' => 8059],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'DAISY', 'newdeposit_score' => 3, 'ID' => 2870],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'IVANN', 'newdeposit_score' => 5, 'ID' => 4933],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'MACEDO', 'newdeposit_score' => 1, 'ID' => 11421],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'PJ', 'newdeposit_score' => null, 'ID' => 5561],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'DARWIN', 'newdeposit_score' => null, 'ID' => 4930],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
    ['year' => 2024, 'month' => 'September', 'db_name' => 'VINCENT', 'newdeposit_score' => 2, 'ID' => 9777],

    ['year' => 2024, 'month' => 'October', 'db_name' => 'RUSTAN', 'newdeposit_score' => null, 'ID' => 2394],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'SALLY', 'newdeposit_score' => 2, 'ID' => 2470],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'NEL', 'newdeposit_score' => null, 'ID' => 2856],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'RUFFY', 'newdeposit_score' => 1, 'ID' => 7870],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'MHEL', 'newdeposit_score' => null, 'ID' => 2852],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'RANDY', 'newdeposit_score' => null, 'ID' => 11422],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'JOMAN', 'newdeposit_score' => null, 'ID' => 2858],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'CCUNANAN', 'newdeposit_score' => null, 'ID' => 9721],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'JHUN', 'newdeposit_score' => null, 'ID' => 3002],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'CHRIS', 'newdeposit_score' => null, 'ID' => 10359],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'ARLENE', 'newdeposit_score' => 2, 'ID' => 8059],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'DAISY', 'newdeposit_score' => 1, 'ID' => 2870],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'IVANN', 'newdeposit_score' => 3, 'ID' => 4933],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'MACEDO', 'newdeposit_score' => 2, 'ID' => 11421],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'MARIE', 'newdeposit_score' => 4, 'ID' => 6379],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'BRY', 'newdeposit_score' => null, 'ID' => 2472],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'PJ', 'newdeposit_score' => 1, 'ID' => 5561],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'DARWIN', 'newdeposit_score' => null, 'ID' => 4930],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'DON', 'newdeposit_score' => null, 'ID' => 2846],
    ['year' => 2024, 'month' => 'October', 'db_name' => 'VINCENT', 'newdeposit_score' => 1, 'ID' => 9777],


];


// $data = [
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'SALLY', 'newdeposit_score' => 1, 'ID' => 2470],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'NEL', 'newdeposit_score' => 0, 'ID' => 2856],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'RUFFY', 'newdeposit_score' => 0, 'ID' => 7870],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 1, 'ID' => 9721],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'JHUN', 'newdeposit_score' => 1, 'ID' => 3002],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'CHRIS', 'newdeposit_score' => 1, 'ID' => 10359],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'ARLENE', 'newdeposit_score' => 1, 'ID' => 8059],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'DAISY', 'newdeposit_score' => 3, 'ID' => 2870],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'IVANN', 'newdeposit_score' => 5, 'ID' => 4933],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'MACEDO', 'newdeposit_score' => 1, 'ID' => 11421],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'MARIE', 'newdeposit_score' => 2, 'ID' => 6379],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'PJ', 'newdeposit_score' => 0, 'ID' => 5561],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'DARWIN', 'newdeposit_score' => 0, 'ID' => 4930],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
//     ['year' => 2024, 'month' => 'September', 'db_name' => 'VINCENT', 'newdeposit_score' => 2, 'ID' => 9777],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'RUSTAN', 'newdeposit_score' => 0, 'ID' => 2394],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'SALLY', 'newdeposit_score' => 2, 'ID' => 2470],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'NEL', 'newdeposit_score' => 0, 'ID' => 2856],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'RUFFY', 'newdeposit_score' => 1, 'ID' => 7870],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'MHEL', 'newdeposit_score' => 0, 'ID' => 2852],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'RANDY', 'newdeposit_score' => 0, 'ID' => 11422],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'JOMAN', 'newdeposit_score' => 0, 'ID' => 2858],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'CCUNANAN', 'newdeposit_score' => 0, 'ID' => 9721],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'JHUN', 'newdeposit_score' => 0, 'ID' => 3002],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'CHRIS', 'newdeposit_score' => 0, 'ID' => 10359],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'ARLENE', 'newdeposit_score' => 2, 'ID' => 8059],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'DAISY', 'newdeposit_score' => 1, 'ID' => 2870],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'IVANN', 'newdeposit_score' => 3, 'ID' => 4933],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'MACEDO', 'newdeposit_score' => 2, 'ID' => 11421],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'MARIE', 'newdeposit_score' => 4, 'ID' => 6379],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'BRY', 'newdeposit_score' => 0, 'ID' => 2472],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'PJ', 'newdeposit_score' => 1, 'ID' => 5561],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'DARWIN', 'newdeposit_score' => 0, 'ID' => 4930],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'DON', 'newdeposit_score' => 0, 'ID' => 2846],
//     ['year' => 2024, 'month' => 'October', 'db_name' => 'VINCENT', 'newdeposit_score' => 1, 'ID' => 9777],
// ];


    // Helper function to get a random date within a month and year
function getRandomDate($month, $year) {
    $startDate = "$year-$month-01";
    $endDate = date("Y-m-t", strtotime($startDate));
    return date("Y-m-d", mt_rand(strtotime($startDate), strtotime($endDate)));
}

foreach ($data as $row) {
    $agent_id = $row['ID'];
    $month = $row['month'];
    $year = $row['year'];
    $new_deposit = $row['newdeposit_score'];

    if ($new_deposit == null){
        $new_deposit = 0;
    }



    if (($new_deposit >  0) && ($agent_id != null)){
            // Insert into memo table
        for ($i = 1; $i <= $new_deposit; $i++) {

            $random_date = getRandomDate(date("m", strtotime($month)), $year);
            $description = "New Deposit For New Customer";
            $sql = "INSERT INTO new_deposit (agent_id, month, year, new_deposit, description, date)
                    VALUES ('$agent_id', '$month', '$year', 10000, '$description', '$random_date')";

            if ($conn->query($sql) === TRUE) {
                echo "New record created successfully for agent_id $agent_id\n";
            } else {
                echo "Error: " . $sql . "\n" . $conn->error;
            }
        }
    }else{
        echo "Dont Insert agent has no new deposit.. or agent has already resigned..";
    }




}

$conn->close();
?>
